apiVersion: v1
kind: Template
metadata:
  name: isis-api-imagestream
  annotations:
    description: >
      This is Isis API ImageStream, this template is meant to be used by Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Core: Isis API'
    version: 0.8.0
    tags: poc,thoth,isis-api,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Isis API ImageStream, this template is meant to be used by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.8.0
  labels:
    template: isis-api-imagestream
    app: thoth
    component: isis-api

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.8.0
      labels:
        app: thoth
        component: isis-api
      name: isis-api
    spec:
      name: ${IMAGE_STREAM_TAG}

parameters:
  - description: Tag of the ImageStream to use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
